name: Deploy React to Github pages

# Trigger the workflow on push to main or pull request to main
on:
  push:
    branches:
      - main
      - "feature/**"
  workflow_dispatch:

# Define jobs
jobs:
  Test:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Installing Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Print node verison
        run: node -v
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci # uses clean install reads requirement frmo json lock file
        #better than npm install
      - name: Run test
        run: npm run test

  Build:
    needs: Test
    runs-on: ubuntu-latest # Use the latest Ubuntu runner
    steps:
      - name: get code
        uses: actions/checkout@v4
      - name: Installing Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: |
          npm run build
          echo "building ....build succesfully"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: dist
  deploy:
    # Add a dependency to the build job
    needs: Build
    runs-on: ubuntu-latest # Use the latest Ubuntu runner
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action
        with:
          token: ${{secrets.GITHUB_TOKEN}}
