name: Deploy

# Trigger the workflow on push to main or pull request to main
on:
  push:
    branches:
      - main
  workflow_dispatch:

# Define jobs
jobs:
  test:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Installing Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Print node verison
        run: node -v
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci # uses clean install reads requirement frmo json lock file
        #better than npm install
      - name: Run test
        run: npm run test

  deploy:
    needs: test
    runs-on: ubuntu-latest # Use the latest Ubuntu runner
    steps:
      - name: get code
        uses: actions/checkout@v4
      - name: Installing Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: deploy
        run: echo "deploying ....Deployed succesfully"
