name: Deploy

# Trigger the workflow on push to main or pull request to main
on:
  push:
    branches:
      - main
  workflow_dispatch:

# Define jobs
jobs:
  test:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Installing Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Print node verison
        run: node -v
      - name: Install dependencies
        run: npm ci # uses clean install reads requirement frmo json lock file
        #better than npm install
      - name: Run test
        run: npm run test
