name: Greeting

# Trigger the workflow on push to main or pull request to main
on:
  push:
    branches:
      - main

# Define jobs
jobs:
  greeting:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        run: echo " hello world"
